import type { Market } from "../market";

const SITE_URL = process.env.NEXT_PUBLIC_SITE_URL ?? "https://roomsforrentatl.com";

export const ATL_MARKET: Market = {
  id: "atl",
  mark: "ATL",
  name: "RoomsForRentATL",
  domain: "RoomsForRentATL.com",
  url: SITE_URL,
  metro: "Atlanta",
  westLabel: "West Atlanta",
  phone: "(678) 490-9917",
  listingSource: "sources",
  tagline: "Furnished rooms for rent in Atlanta — next day move in.",
  description:
    "Furnished rooms for rent in Atlanta — weekly, no lease, next-day move-in. All-in pricing with utilities & WiFi included. Book a PadSplit room today.",
  seoTitle: "RoomsForRentATL — Furnished Rooms for Rent in Atlanta, Next-Day Move In",
  socialTitle: "Apply Today, Move in Tomorrow",
  keywords: [
    "rooms for rent Atlanta",
    "furnished rooms Atlanta",
    "furnished room for rent Atlanta weekly",
    "next day move in Atlanta",
    "weekly rooms Atlanta",
    "PadSplit Atlanta",
    "PadSplit rooms Atlanta",
    "no lease room rental Atlanta",
    "co-living Atlanta",
    "shared house Atlanta",
    "flexible lease room Atlanta",
    "affordable room for rent Atlanta",
    "private bedroom for rent Atlanta",
    "weekly rent room Atlanta",
    "room for rent Decatur",
    "room for rent Stone Mountain",
    "room for rent Snellville",
  ],
  heroKicker: "Furnished rooms across Atlanta",
  heroPhoto: {
    mobile: "/photos/candace-room-1-wide.jpg",
    desktop: "/photos/mora-room-1-lg.jpg",
  },
  cardPhotos: {
    "35011": {
      src: "/photos/mora-room-2.jpg",
      alt: "Furnished bedroom with a bed and shelving, kitchen through the door, at The Mora House",
    },
    "8299": {
      src: "/photos/candace-room-3.jpg",
      alt: "Furnished bedroom with a bed, desk, and window at The Candace House",
    },
  },
  seoHeading: "Furnished rooms for rent in Atlanta, GA",
  seoBody:
    "Looking for an affordable room to rent in Atlanta? We have furnished private bedrooms in shared homes across the entire Atlanta metro area with no long lease and weekly or biweekly pay. Every furnished room on this site is booked through PadSplit, with utilities, parking and Wi-Fi included. Once you're approved, you can move in as soon as the next day.",
  footerLine: "Furnished rooms for rent in Atlanta. Move in as soon as tomorrow.",
  featuredSources: [
    "https://www.padsplit.com/rooms-for-rent/listing/35011",
    "https://www.padsplit.com/rooms-for-rent/listing/8299",
    "https://www.padsplit.com/rooms-for-rent/listing/11889",
    "https://www.padsplit.com/rooms-for-rent/listing/152",
    "https://www.padsplit.com/rooms-for-rent/listing/39708",
  ],
  showPageFaq: false,
  showCityList: false,
  referral: {
    code: "B2C2060F",
    overrides: {
      covilla: "0DC68BAB",
    },
  },
  padsplit: {
    searchPath: "atlanta-ga",
    state: "ga",
    bounds: {
      latMax: "33.9698383740918",
      lngMax: "-84.10153814955288",
      latMin: "33.497148095320355",
      lngMin: "-84.56500806987017",
    },
  },
  cities: [
    { slug: "decatur", name: "Decatur" },
    { slug: "stone-mountain", name: "Stone Mountain" },
    { slug: "atlanta", name: "Atlanta" },
    { slug: "east-point", name: "East Point" },
    { slug: "norcross", name: "Norcross" },
    { slug: "marietta", name: "Marietta" },
    { slug: "riverdale", name: "Riverdale" },
    { slug: "avondale-estates", name: "Avondale Estates" },
    { slug: "covington", name: "Covington" },
    { slug: "college-park", name: "College Park" },
    { slug: "kennesaw", name: "Kennesaw" },
    { slug: "canton", name: "Canton" },
    { slug: "jonesboro", name: "Jonesboro" },
    { slug: "fairburn", name: "Fairburn" },
    { slug: "fayetteville", name: "Fayetteville" },
    { slug: "newnan", name: "Newnan" },
    { slug: "snellville", name: "Snellville" },
  ],
  areas: [
    { slug: "decatur", label: "Decatur", pattern: "\\bdecatur\\b" },
    { slug: "stone-mountain", label: "Stone Mountain", pattern: "\\bstone\\s+mountain\\b" },
    { slug: "snellville", label: "Snellville", pattern: "\\bsnellville\\b" },
    { slug: "marietta", label: "Marietta", pattern: "\\bmarietta\\b" },
    { slug: "east-point", label: "East Point", pattern: "\\beast\\s+point\\b" },
    { slug: "norcross", label: "Norcross", pattern: "\\bnorcross\\b" },
    { slug: "college-park", label: "College Park", pattern: "\\bcollege\\s+park\\b" },
    { slug: "avondale-estates", label: "Avondale Estates", pattern: "\\bavondale(?:\\s+estates)?\\b" },
    { slug: "kennesaw", label: "Kennesaw", pattern: "\\bkennesaw\\b" },
    { slug: "atlanta", label: "South Atlanta", pattern: "\\bsouth\\s+atlanta\\b", wide: true, cityIncludes: "south atlanta" },
    { slug: "atlanta", label: "Buckhead", pattern: "\\bbuckhead\\b", wide: true },
    { slug: "atlanta", label: "Midtown", pattern: "\\bmidtown\\b", wide: true },
    { slug: "atlanta", label: "Atlanta", pattern: "\\batlanta\\b", cityIncludes: "atlanta", cityExcludes: "south atlanta" },
  ],
  areaChips: ["Decatur", "Stone Mountain", "South Atlanta", "Snellville", "Atlanta"],
  metroLinkIsCity: false,
  shortHouses: {
    mora: "35011",
    candace: "8299",
    raven: "11889",
    chestnut: "152",
    willow: "39708",
  },
  og: {
    alt: "Furnished rentals in Atlanta",
    letter: "R",
    word: "Rooms",
    line1: "Furnished rooms in Atlanta.",
    line2: "Next Day Move In",
    sub: "All-in weekly pricing · utilities & WiFi included",
    chips: ["Fully furnished", "Utilities + WiFi included", "Stay as long as you need"],
  },
  homesSeoTitle: "HomesForRentATL — Furnished Private Rentals in Atlanta, GA",
  homesKeywords: [
    "private rentals Atlanta",
    "furnished rentals Atlanta",
    "furnished apartments for rent Atlanta",
    "homes for rent Atlanta",
    "monthly rentals Atlanta",
    "furnished monthly rental Atlanta",
    "no lease apartment Atlanta",
    "short term furnished rental Atlanta",
    "studio for rent Atlanta",
    "furnished studio Atlanta",
    "utilities included apartment Atlanta",
    "furnished apartment Snellville",
    "furnished apartment Decatur",
  ],
  homesOg: {
    alt: "Furnished rentals in Atlanta",
    letter: "H",
    word: "Homes",
    line1: "Furnished rentals in Atlanta.",
    line2: "Your own private space",
    sub: "Monthly lease · utilities included",
    chips: ["Fully furnished", "Utilities included", "A place that's all yours"],
  },
  homesSister: {
    label: "Looking for a single room?",
    name: "RoomsForRentATL.com",
    url: "https://roomsforrentatl.com",
  },
  homesRentalsTitle: "Furnished Private Rentals & Apartments for Rent in Atlanta, GA",
  homesRentalsDescription:
    "Furnished private rentals and apartments for rent in the Atlanta area — a full unit that's all yours, monthly lease, utilities included. Apply online today.",
};

export const ACTIVE_MARKET = ATL_MARKET;
